
dataset_QA_survey=[['Ti consideri un videoterminalista?','Si','Il lavoratore è considerato tale se utilizza sistematicamente e abitualmente un videoterminale per almeno venti ore settimanali, escludendo le interruzioni previste dalla normativa.'],
                   ['Usi in modo sistematico o abituale un videoterminale per almeno 20 ore la settimana?','Si','Nel caso positivo l utente può considerasi un videoterminalista, altriemnti no.'],
                   ['Consideri il videoterminale anche il computer portatile?','Si','Dal punto di vista normativo, il videoterminale viene definito come qualsiasi schermo alfanumerico o grafico, indipendentemente dal tipo di tecnologia di visualizzazione utilizzata.'],
                   ['Se usi un computer portatile ti hanno fornito la tastiera esterna?','Si','La tastiera va posizionata a una distanza tale da consentire una digitazione rilassata, con i polsi in posizione neutra e non piegati verso l’alto o verso il basso.'],
                   ['Se usi un computer portatile ti hanno fornito il mouse esterno?','Si'],
                   ['Un supporto?','Si'],
                   ['Hai mai avvertito affaticamento visivo?','No','Infine, per prevenire il senso di stanchezza e migliorare la circolazione, è consigliabile alternare il lavoro al videoterminale con brevi pause ogni due ore, durante le quali è utile alzarsi, muoversi e distogliere lo sguardo dallo schermo per rilassare gli occhi.Seguire queste indicazioni permette di lavorare in modo più confortevole e sicuro, riducendo il rischio di disturbi muscolo-scheletrici e affaticamento visivo.'],
                   ['Soffri di mal di testa dopo aver usato il videoterminale?','No','Infine, per prevenire il senso di stanchezza e migliorare la circolazione, è consigliabile alternare il lavoro al videoterminale con brevi pause ogni due ore, durante le quali è utile alzarsi, muoversi e distogliere lo sguardo dallo schermo per rilassare gli occhi. Seguire queste indicazioni permette di lavorare in modo più confortevole e sicuro, riducendo il rischio di disturbi muscolo-scheletrici e affaticamento visivo. £'],
                   ['Hai dolori muscolari (collo, spalle, schiena) dopo lunghe sessioni di lavoro?','No','Infine, per prevenire il senso di stanchezza e migliorare la circolazione, è consigliabile alternare il lavoro al videoterminale con brevi pause ogni due ore, durante le quali è utile alzarsi, muoversi e distogliere lo sguardo dallo schermo per rilassare gli occhi.Seguire queste indicazioni permette di lavorare in modo più confortevole e sicuro, riducendo il rischio di disturbi muscolo-scheletrici e affaticamento visivo. £'],
                   ['Riscontri problemi di secchezza oculare o irritazione?','No','Infine, per prevenire il senso di stanchezza e migliorare la circolazione, è consigliabile alternare il lavoro al videoterminale con brevi pause ogni due ore, durante le quali è utile alzarsi, muoversi e distogliere lo sguardo dallo schermo per rilassare gli occhi. Seguire queste indicazioni permette di lavorare in modo più confortevole e sicuro, riducendo il rischio di disturbi muscolo-scheletrici e affaticamento visivo. £'],
                   ['Fai 15 minuti di pausa ogni due ore di applicazione continuativa al videoterminale?','Si','Infine, per prevenire il senso di stanchezza e migliorare la circolazione, è consigliabile alternare il lavoro al videoterminale con brevi pause ogni due ore, durante le quali è utile alzarsi, muoversi e distogliere lo sguardo dallo schermo per rilassare gli occhi. Seguire queste indicazioni permette di lavorare in modo più confortevole e sicuro, riducendo il rischio di disturbi muscolo-scheletrici e affaticamento visivo. £'],
                   ['L’ambiente dove lavori è illuminato in modo che finestre e lampade ti creino fenomeni di riflesso o di abbagliamento diretto o indiretto?','Si', 'L’illuminazione della stanza deve essere adeguata: la luce naturale non deve provocare riflessi sullo schermo e l’illuminazione artificiale deve essere uniforme, evitando abbagliamenti o contrasti eccessivi. È preferibile posizionare la postazione di lavoro lateralmente rispetto alle finestre, piuttosto che di fronte o alle spalle, per ridurre l’affaticamento visivo.'],
                   ['Rispetto alla tua posizione di lavoro l’illuminazione naturale o artificiale dell’ambiente crea riflessi o ti potrebbe abbagliare?','No','L’illuminazione della stanza deve essere adeguata: la luce naturale non deve provocare riflessi sullo schermo e l’illuminazione artificiale deve essere uniforme, evitando abbagliamenti o contrasti eccessivi. È preferibile posizionare la postazione di lavoro lateralmente rispetto alle finestre, piuttosto che di fronte o alle spalle, per ridurre l’affaticamento visivo.'],
                   ['Ti alzi spesso dalla postazione per fare altre attività come recupare i fogli della stampante, archiviare la documentazione, consultare un collega?','No'],
                   ['Esegui esercizi di stretching per prevenire affaticamenti?','Si'],
                   ['Pensi di mantenere una postura corretta quando sei seduto?','Si'],
                   ['Le dimensioni del tuo piano di lavoro sono sufficienti da permettere una disposizione flessibile dello schermo, della tastiera o di altri compomenti accessori come il mouse?','Si'],
                   ['Il tuo piano di lavoro è di misura almeno 120 x 80 cm?','Si'],
                   ['Il tuo piano di lavoro è di colore chiaro con una superficie poco riflettente?','Si'],
                   ['Quando digiti sulla tastiera il tavolo vibra?','No'],
                   ['Quando ti appoggi su qualsiasi lato del piano da lavoro, il tavolo si inclina?','No'],
                   ['Lo spazio sotto il tavolo è adeguato [almeno tra 70 e 80 cm] per i movimenti delle gambe e per infilarvi sotto il sedile?','Si'],
                   ['Il piano di lavoro è regolabile in altezza?','Si'],
                   ['Da seduto i piedi poggiano sul pavimento?','Si'],
                   ['Se i tuoi piedi non poggiano sul pavimento hai un poggiapiedi?','Si'],
                   ['Il poggiapiede che hai è sufficientemente ampio, mobile e antisdrucciolevole?','Si'],
                   ['Il sedile è comodo, stabile e regolare in altezza?','Si'],
                   ['Il sedile ti permette libertà di movimento per facilitare i cambi di posizione?','Si'],
                   ['Lo schienale è regolabile in altezza, almeno 50cm al di sopra del sedile?','Si'],
                   ['Lo schienale ti assicura un adeguato supporto alla regione dorso lombare?','Si'],
                   ['Quando sei seduto le spalle sono rilassate?','Si'],
                   ['Quando sei seduto i gomiti pendano comodamente lungo i fianchi?','Si'],
                   ['Quando sei seduto gli avambracci sono in posizione orizzontale e non inclinati verso l’alto o verso il basso?','Si'],
                   ['Lo schienale e la seduta sono profilati e smussati?','Si'],
                   ['L’imbottitura è spessa e semi-rigida?','Si'],
                   ['Il rivestimento della sedia è traspirante?','Si'],
                   ['Il monitor è inclinabile?','Si','Il monitor deve essere collocato di fronte a chi lavora, a una distanza compresa tra 50 e 70 cm dagli occhi, con la parte superiore dello schermo all’altezza dello sguardo o leggermente al di sotto. Questo accorgimento evita tensioni al collo e affaticamento visivo. Inoltre, lo schermo deve essere inclinato leggermente all’indietro per migliorare la leggibilità e ridurre il riflesso della luce.'],
                   ['Il monitor è ruotabile?','Si'],
                   ['Hai distanziato il monitor a 50/70 cm dai tuoi occhi?','Si','Il monitor deve essere collocato di fronte a chi lavora, a una distanza compresa tra 50 e 70 cm dagli occhi, con la parte superiore dello schermo all’altezza dello sguardo o leggermente al di sotto. Questo accorgimento evita tensioni al collo e affaticamento visivo. Inoltre, lo schermo deve essere inclinato leggermente all’indietro per migliorare la leggibilità e ridurre il riflesso della luce.'],
                   ['Quando sei davanti al monitor, e guardi in direzione orizzontale, fissi il bordo superiore dello schermo?','Si'],
                   ['Puoi regolare contrasto e illuminazione dello schermo?','Si'],
                   ['La tastiera è separata dallo schermo?','si'],
                   ['La tastiera è dotata di un meccanismo che ne varia la pendenza?','Si'],
                   ['Lo spazio sul piano di lavoro ti consente l’appoggio delle mani e degli avambracci?','Si'],
                   ['La tastiera ha una superficie opaca e antiriflesso?','Si']]

