
dataset_QA_survey=[['Ti consideri un videoterminalista?','Si'],
                   ['Usi in modo sistematico o abituale un videoterminale per almeno 20 ore la settimana?','Si'],
                   ['Consideri il videoterminale anche il computer portatile?','Si'],
                   ['Se usi un computer portatile ti hanno fornito la tastiera esterna?','Si'],
                   ['Il mouse?','Si'],
                   ['Un supporto?','Si'],
                   ['Hai mai avvertito affaticamento visivo?','Null'],
                   ['Soffri di mal di testa dopo aver usato il videoterminale?','Null'],
                   ['Hai dolori muscolari (collo, spalle, schiena) dopo lunghe sessioni di lavoro?','Null'],
                   ['Riscontri problemi di secchezza oculare o irritazione?','Null'],
                   ['Fai 15 minuti di pausa ogni due ore di applicazione continuativa al videoterminale?','Si'],
                   ['L’ambiente dove lavori è illuminato in modo che finestre e lampade ti creino fenomeni di riflesso o di abbagliamento diretto o indiretto?','No'],
                   ['Rispetto alla tua posizione di lavoro l’illuminazione naturale o artificiale dell’ambiente crea riflessi o ti potrebbe abbagliare?','No'],
                   ['Ti alzi spesso dalla postazione per fare altre attività come recupare i fogli della stampante, archiviare la documentazione, consultare un collega?','No'],
                   ['Esegui esercizi di stretching per prevenire affaticamenti?','Si'],
                   ['Pensi di mantenere una postura corretta quando sei seduto?','Si'],
                   ['Le dimensioni del tuo piano di lavoro sono sufficienti da permettere una disposizione flessibile dello schermo, della tastiera o di altri compomenti accessori come il mouse?','Si'],
                   ['Il tuo piano di lavoro è di misura almeno 120 x 80 cm?','Si'],
                   ['Il tuo piano di lavoro è di colore chiaro con una superficie poco riflettente?','Si'],
                   ['Quando digiti sulla tastiera il tavolo vibra?','No'],
                   ['Quando ti appoggi su qualsiasi lato del piano da lavoro, il tavolo si inclina?','No'],
                   ['Lo spazio sotto il tavolo è adeguato [almeno tra 70 e 80 cm] per i movimenti delle gambe e per infilarvi sotto il sedile?','Si'],
                   ['Il piano di lavoro è regolabile in altezza?','Si'],
                   ['Da seduto i piedi poggiano sul pavimento?','Si'],
                   ['Se i tuoi piedi non poggiano sul pavimento hai un poggiapiedi?','Si'],
                   ['Il poggiapiede che hai è sufficientemente ampio, mobile e antisdrucciolevole?','Si'],
                   ['Il sedile è comodo, stabile e regolare in altezza?','Si'],
                   ['Il sedile ti permette libertà di movimento per facilitare i cambi di posizione?','Si'],
                   ['Lo schienale è regolabile in altezza, almeno 50cm al di sopra del sedile?','Si'],
                   ['Lo schienale ti assicura un adeguato supporto alla regione dorso lombare?','Si'],
                   ['Quando sei seduto le spalle sono rilassate?','Si'],
                   ['Quando sei seduto i gomiti pendano comodamente lungo i fianchi?','Si'],
                   ['Quando sei seduto gli avambracci sono in posizione orizzontale e non inclinati verso l’alto o verso il basso?','Si'],
                   ['Lo schienale e la seduta sono profilati e smussati?','Si'],
                   ['L’imbottitura è spessa e semi-rigida?','Si'],
                   ['Il rivestimento della sedia è traspirante?','Si'],
                   ['Il monitor è inclinabile?','Si'],
                   ['Il monitor è ruotabile?','Si'],
                   ['Hai distanziato il monitor a 50/70 cm dai tuoi occhi?','Si'],
                   ['Quando sei davanti al monitor, e guardi in direzione orizzontale, fissi il bordo superiore dello schermo?','Si'],
                   ['Puoi regolare contrasto e illuminazione dello schermo?','Si'],
                   ['La tastiera è separata dallo schermo?','si'],
                   ['La tastiera è dotata di un meccanismo che ne varia la pendenza?','Si'],
                   ['Lo spazio sul piano di lavoro ti consente l’appoggio delle mani e degli avambracci?','Si'],
                   ['La tastiera ha una superficie opaca e antiriflesso?','Si']]

